---
version: "2"
checks:
  method-count:
    config:
      threshold: 30
exclude_patterns:
  - "build/"
  - "doc/"
plugins:
  pep8:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
