---
version: "2"
checks:
  argument-count:
    config:
      threshold: 5
exclude_patterns:
  - "build/"
  - "doc/"
  - "bin/"
  - "test/"
  - "setup.py"
plugins:
  pep8:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
