language:
  python

python:
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install -U pip
  - pip --version
  - pip install -r requirements-dev.txt
  - python bin/downloads.py

before_script:
  - which python

script:
  - python ./runtest.py -e -a
