language:
  python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

before_install:
  - export REQUIREMENTS_TXT=`python -c 'import sys;print("requirements" + str(sys.version_info.major) + "-dev.txt")'`
  - echo "REQUIREMENTS_TXT=$REQUIREMENTS_TXT"

install:
  - pip install -U pip
  - pip --version
  - pip install -r "$REQUIREMENTS_TXT"
  - pip install coveralls
  - pip install coverage
  - pip install -e .
  - python bin/downloads.py

before_script:
  - which python

script:
  - coverage run --source=sconstool.loader -m unittest discover -t . -s test/unit
  - TESTCOMMON_PASS_SKIPS=1 python runtest --verbose=2 -e test/system

after_script:
  - coveralls
